<?php
declare(strict_types=1);

namespace Joist\Plan;

use Joist\Container;
use Joist\Elementor\WriteException;

/**
 * @purpose Translate natural-language intent into a structured Plan.
 *
 * Two paths:
 *   - Configured Anthropic API key → real Claude call with a brand-aware system
 *     prompt that produces strict JSON Plan output
 *   - No key → deterministic template fallback so the loop can be demoed
 *     without a paid API key
 *
 * Either way, returns the steps array shaped for PlanStore::create(). The
 * controller wraps this into a Plan row and the existing approve/execute
 * flow takes over from there.
 *
 * Output contract — always V3-compatible Elementor shapes (elType: container,
 * elType: widget) so PatchEngine + DocumentWriter route the same way human-
 * built pages do. We never emit V4 atomic `e-*` shapes from this generator
 * because upstream #35888 currently corrupts those saves silently on V4
 * installs.
 */
final class PlanGenerator
{
    private const ANTHROPIC_URL = 'https://api.anthropic.com/v1/messages';
    private const MODEL = 'claude-opus-4-7';

    public function generate(string $intent, ?int $pageId = null): array
    {
        if ($intent === '' || mb_strlen($intent) < 5) {
            throw new WriteException(
                'plan_generate.intent_too_short',
                'Intent must be at least 5 characters.',
                422
            );
        }

        $apiKey = $this->apiKey();
        if ($apiKey === '') {
            // Fallback path — produce a structured template so the user can
            // see the loop work end-to-end without spending Anthropic money.
            return $this->templateSteps($intent);
        }

        return $this->callClaude($intent, $pageId, $apiKey);
    }

    /** Return source for the API key — env first, wp_option second. */
    private function apiKey(): string
    {
        $env = getenv('JOIST_CLAUDE_API_KEY');
        if (is_string($env) && $env !== '') return trim($env);
        $opt = get_option('joist_claude_api_key', '');
        return is_string($opt) ? trim($opt) : '';
    }

    /** Build the steps the generator produces when no API key is available. */
    private function templateSteps(string $intent): array
    {
        $headline = $this->extractTopic($intent);
        return [
            [
                'op' => 'insert',
                'path' => '/elements/-',
                'element' => [
                    'elType' => 'container',
                    'settings' => [
                        'content_width' => 'boxed',
                        'padding' => [
                            'unit' => 'px',
                            'top' => '80', 'right' => '20', 'bottom' => '80', 'left' => '20',
                            'isLinked' => false,
                        ],
                    ],
                    'elements' => [
                        [
                            'elType' => 'widget',
                            'widgetType' => 'heading',
                            'settings' => [
                                'title' => $headline,
                                'header_size' => 'h1',
                                'align' => 'center',
                            ],
                        ],
                        [
                            'elType' => 'widget',
                            'widgetType' => 'text-editor',
                            'settings' => [
                                'editor' => '<p style="text-align:center;font-size:18px;line-height:1.55;max-width:640px;margin:0 auto;">'
                                    . esc_html('Generated by Joist from the prompt: ')
                                    . '<em>' . esc_html($intent) . '</em>'
                                    . '. This is the template-mode fallback — configure JOIST_CLAUDE_API_KEY (env) or the joist_claude_api_key option to engage the real generator.</p>',
                            ],
                        ],
                        [
                            'elType' => 'widget',
                            'widgetType' => 'button',
                            'settings' => [
                                'text' => 'Read the spec',
                                'align' => 'center',
                                'link' => ['url' => 'https://github.com/ckrohg/joist', 'is_external' => 'on'],
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }

    /** Tiny noun-extractor — keeps the headline tidy without spending tokens. */
    private function extractTopic(string $intent): string
    {
        // Strip the most common imperative prefixes so we end with something
        // close to a topic noun phrase.
        $stripped = preg_replace(
            '/^(build|create|make|generate|design|draft|sketch|prototype)\s+(a|an|the|me a|me an|me the)?\s*/i',
            '',
            trim($intent)
        );
        $stripped = trim((string) $stripped, " \t\n\r\0\x0B.,");
        if ($stripped === '') $stripped = $intent;
        // Title-case the first segment.
        $words = preg_split('/\s+/', $stripped) ?: [];
        $words = array_slice($words, 0, 8);
        $words[0] = ucfirst($words[0] ?? '');
        return implode(' ', $words);
    }

    /**
     * Call Anthropic's Messages API with a brand-aware system prompt and a
     * tight JSON output schema. Throws WriteException on transport / parse
     * failures.
     */
    private function callClaude(string $intent, ?int $pageId, string $apiKey): array
    {
        $system = $this->buildSystemPrompt();
        $body = [
            'model' => self::MODEL,
            'max_tokens' => 2048,
            'system' => [
                ['type' => 'text', 'text' => $system, 'cache_control' => ['type' => 'ephemeral']],
            ],
            'messages' => [
                [
                    'role' => 'user',
                    'content' => 'Produce the Plan JSON for the following intent. Output JSON only, no prose, no markdown fence.'
                        . "\n\nINTENT: " . $intent
                        . ($pageId ? "\n\nPAGE_ID (existing page being edited): " . $pageId : ''),
                ],
            ],
        ];

        $resp = wp_remote_post(self::ANTHROPIC_URL, [
            'timeout' => 60,
            'headers' => [
                'content-type' => 'application/json',
                'x-api-key' => $apiKey,
                'anthropic-version' => '2023-06-01',
            ],
            'body' => wp_json_encode($body),
        ]);

        if (is_wp_error($resp)) {
            throw new WriteException(
                'plan_generate.transport_failed',
                'Anthropic API transport failed: ' . $resp->get_error_message(),
                502
            );
        }
        $code = (int) wp_remote_retrieve_response_code($resp);
        $raw = (string) wp_remote_retrieve_body($resp);
        if ($code !== 200) {
            throw new WriteException(
                'plan_generate.api_error',
                "Anthropic API returned HTTP {$code}",
                502,
                ['anthropic_status' => $code, 'body_head' => mb_substr($raw, 0, 300)]
            );
        }
        $decoded = json_decode($raw, true);
        if (!is_array($decoded) || empty($decoded['content'])) {
            throw new WriteException(
                'plan_generate.unexpected_response',
                'Anthropic API returned an unexpected response shape.',
                502
            );
        }
        $text = '';
        foreach ($decoded['content'] as $block) {
            if (is_array($block) && ($block['type'] ?? '') === 'text') {
                $text .= (string) ($block['text'] ?? '');
            }
        }
        $text = trim($text);
        // Tolerate optional ```json fences.
        $text = preg_replace('/^```(?:json)?\s*/i', '', $text);
        $text = preg_replace('/\s*```$/', '', $text);
        $plan = json_decode((string) $text, true);
        if (!is_array($plan) || !isset($plan['steps']) || !is_array($plan['steps'])) {
            throw new WriteException(
                'plan_generate.invalid_plan_json',
                'Generator response did not contain a valid steps array.',
                502,
                ['response_head' => mb_substr((string) $text, 0, 300)]
            );
        }
        return $plan['steps'];
    }

    /**
     * Construct the system prompt. Brand-aware, forbids slop, constrains the
     * output to V3-compatible shapes the rest of Joist's pipeline understands.
     */
    private function buildSystemPrompt(): string
    {
        return <<<PROMPT
You are Joist's plan generator. You turn a one-sentence intent into a structured Elementor Plan — a JSON object the rest of Joist's pipeline executes through schema-validated, audited, hash-checked saves.

OUTPUT CONTRACT
Return strict JSON with this exact top-level shape (no prose, no markdown fence):
{
  "steps": [
    { "op": "insert", "path": "/elements/-", "element": { … } },
    …
  ]
}

ELEMENT SHAPE — use V3-compatible Elementor structures only:
- Root nodes are containers: `{ "elType": "container", "settings": {...}, "elements": [...] }`
- Inside containers, nest widgets: `{ "elType": "widget", "widgetType": "<slug>", "settings": {...} }`
- Allowed widget slugs (and only these): heading, text-editor, button, image, icon, divider, spacer, video, html, social-icons, icon-list, star-rating
- Heading settings: `title` (string), `header_size` (h1|h2|h3|h4|h5|h6), `align` (left|center|right)
- Text-editor settings: `editor` (HTML string)
- Button settings: `text` (string), `align`, `link` ({ url, is_external })
- Image settings: `image` ({ url, alt })
- Container settings should include `content_width` (boxed|full) and reasonable `padding` ({ unit:"px", top, right, bottom, left, isLinked:false })

DESIGN AESTHETIC — Joist's Foundry brand language:
- Editorial-engineering: confident wordmark-grade typography, generous whitespace, warm dark surfaces (although we don't set background colors at the element level)
- Forbidden: indigo/purple gradients, "Build the future of X", "Empower your", "Revolutionize", "Unleash", AI-stock-photo aesthetics, marketing-speak superlatives
- Preferred: direct sentences, concrete nouns, scannable hierarchy. The reader should sense craft from the first headline alone.

STRUCTURE GUIDELINES
- Most pages: 4–7 root containers stacked vertically. Hero → value props (3 column container, or 3 stacked widgets) → secondary section → CTA → footer-style closer.
- Hero containers: extra padding (80–120px top/bottom), centered align, single H1 + supporting text-editor + a button.
- Use Joist's voice: specific, opinionated, no fluff. Headlines are propositions, not labels.

EXAMPLES OF GOOD HEADLINES
- "Joinery the way joiners would build it."
- "Software that holds the floor up, not the floor down."
- "Open-source agentic backbone for Elementor."

EXAMPLES OF BAD HEADLINES (do not produce)
- "Welcome to our website" / "About us"
- "Empower your business with AI-powered solutions"
- "Build the future of X"
- Anything mentioning "synergy", "leverage", "next-gen", "game-changing"

OUTPUT ONLY THE JSON OBJECT. NO PROSE. NO MARKDOWN FENCE.
PROMPT;
    }
}
