<?php
declare(strict_types=1);

namespace Joist\Core;

/**
 * Canonicalize Elementor element trees into a deterministic byte sequence
 * and SHA-256 hash them. This is the OCC primitive — every read returns
 * a hash; every write echoes the hash it was planned against; mismatch
 * triggers a 409.
 *
 * Canonicalization rules:
 *   1. Recursively sort object keys.
 *   2. Strip transient render-time fields the editor adds.
 *   3. Normalize array vs object empty-state (PHP json_encode quirk: empty
 *      array → [], empty assoc → {}). We force objects for settings/elements.
 *   4. UTF-8 + JSON_UNESCAPED_SLASHES, no pretty-printing.
 */
final class Hasher
{
    /** @var list<string> Fields stripped during strict canonicalization. */
    private const TRANSIENT_FIELDS = [
        '_temp_id',
    ];

    /**
     * Wave 2 (2026-05-31) — fields stripped during *lenient* canonicalization
     * for the silent-save-failure check on V4 atomic.
     *
     * V4's atomic transformer pipeline auto-adds these fields on every save,
     * even when input doesn't include them. Treating their addition as
     * "corruption" false-positives constraint #16. Wave 1's structuralDiff
     * confirmed `isInner` is added to every container on save; `id` is
     * regenerated by Elementor's id-manager when missing.
     *
     * This is the iterative strip-list — extend it when wave-1 diff data
     * reveals additional benign V4 normalizations.
     *
     * @var list<string>
     */
    private const V4_AUTO_FIELDS = [
        'isInner',          // V4 always adds to containers
        'id',               // Elementor regenerates / preserves; not semantically meaningful for shape
        // Wave 3 (2026-05-31) — V4 atomic-element infrastructure fields.
        // The atomic transformer adds these to every atomic element (e-*)
        // even when input doesn't include them. Never user-authored.
        'styles',           // atomic style system; empty array by default
        'interactions',     // atomic interactions API; empty array by default
        'editor_settings',  // editor-only UI state; empty array by default
        'version',          // atomic schema version; "0.0" by default
    ];

    public function forElements(array $elements): string
    {
        return 'sha256:' . hash('sha256', $this->canonicalize($elements, false));
    }

    /**
     * Wave 2: lenient hash that ignores V4 auto-added fields. Used by
     * AtomicDocumentWriter's silent-save-failure check to distinguish
     * benign V4 normalization from real #35888 silent-corruption.
     *
     * If forElementsLenient(intended) == forElementsLenient(verified), the
     * tree is shape-equivalent — V4's transformer only added fields it
     * always adds, no settings were dropped, no children went missing.
     */
    public function forElementsLenient(array $elements): string
    {
        return 'sha256:' . hash('sha256', $this->canonicalize($elements, true));
    }

    public function forPage(int $postId): string
    {
        // Read through Elementor's documented API, not raw postmeta.
        $document = \Elementor\Plugin::$instance->documents->get($postId);
        if (!$document || !$document->is_built_with_elementor()) {
            return 'sha256:' . hash('sha256', '[]');
        }
        $data = $document->get_elements_data();
        return $this->forElements(is_array($data) ? $data : []);
    }

    /**
     * Wave 2: lenient counterpart to forPage().
     */
    public function forPageLenient(int $postId): string
    {
        $document = \Elementor\Plugin::$instance->documents->get($postId);
        if (!$document || !$document->is_built_with_elementor()) {
            return 'sha256:' . hash('sha256', '[]');
        }
        $data = $document->get_elements_data();
        return $this->forElementsLenient(is_array($data) ? $data : []);
    }

    private function canonicalize(array $elements, bool $lenient): string
    {
        $normalized = $this->normalizeNode($elements, $lenient);
        $json = wp_json_encode($normalized, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        return $json === false ? '[]' : $json;
    }

    /**
     * Recursively normalize: sort keys, strip transients (+ V4 auto-fields
     * in lenient mode).
     *
     * @param mixed $node
     * @return mixed
     */
    private function normalizeNode($node, bool $lenient = false)
    {
        if (is_array($node)) {
            // Detect sequential array (list) vs assoc.
            if ($this->isList($node)) {
                $out = [];
                foreach ($node as $child) {
                    $out[] = $this->normalizeNode($child, $lenient);
                }
                return $out;
            }
            $out = [];
            foreach ($node as $key => $value) {
                if (in_array($key, self::TRANSIENT_FIELDS, true)) {
                    continue;
                }
                if ($lenient && in_array($key, self::V4_AUTO_FIELDS, true)) {
                    continue;
                }
                // Wave 2.2 (2026-05-31) — V4 adds `elements: []` to every
                // widget node even though widgets cannot contain children.
                // Strip empty `elements` arrays in lenient mode so widget
                // nodes hash-equivalently whether or not V4 added the key.
                // Non-empty `elements` (containers with actual children) are
                // preserved — they're semantically meaningful.
                if ($lenient && $key === 'elements' && is_array($value) && count($value) === 0) {
                    continue;
                }
                $out[$key] = $this->normalizeNode($value, $lenient);
            }
            ksort($out, SORT_STRING);
            return $out;
        }
        return $node;
    }

    private function isList(array $arr): bool
    {
        if (function_exists('array_is_list')) {
            return array_is_list($arr);
        }
        $i = 0;
        foreach ($arr as $k => $_) {
            if ($k !== $i++) return false;
        }
        return true;
    }
}
